name = "NCNBD"
uuid = "76100c40-129e-4398-bc8a-8d92901b12c9"
authors = ["Christian Fuellner"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
