name = "DynamicSDDiP"
uuid = "13dd0c9c-319d-47c7-ae8d-0241c720e43f"
authors = ["Christian Fuellner"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
